### ISSUE TITLE
Hexadecimal values should be in uppercase

### ISSUE THREAD

**Issue by piotte13** [piotte13/SIMD-Visualiser#18]

**Comment by lemire** [comment]
Maybe. But both JavaScript and Python default on lower cased hexadecimal numbers.

Maybe you want to flesh out the rationale?

**Comment by piotte13** [comment]
According to https://en.wikipedia.org/wiki/Hexadecimal, the most common representation for hexadecimals is uppercase. Also, under "Written representation" paragraph, I found:

Unix (and related) shells, AT&T assembly language and likewise the C programming language (and its syntactic descendants such as C++, C#, D, Java, JavaScript, Python and Windows PowerShell) use the prefix 0x for numeric constants represented in hex: 0x5A3.

**Comment by lemire** [comment]
I personally favor uppercase letters...  

As for the "0x" prefix, it is indeed standard but in our case, it will add quite a bit of text to our graphical presentation.

**Comment by piotte13** [comment]
Right.  It is not my intention to add the "0x" prefix.
